### ISSUE TITLE
Building costs grow too quickly to sustain games beyond an hour

### ISSUE THREAD

**Issue by tronster** [piesku/duszki#3]
Looking at the formula for building costs it becomes prohibitively expensive for a player to purchase buildings after the first hour of play.  From generator.ts: `return gen.StartingCost * gen.CostFactor ** own_count;`

![duszki building costs - jam values](https://user-images.githubusercontent.com/907833/193963099-f4df7f17-2970-4ae0-8b2e-d8833ddbca02.png)

Some type of dampening should be considered for `own_count`, perhaps dividing it by 2, 3 or even 4 (shown below):

![duszki building costs - dampened own_cost](https://user-images.githubusercontent.com/907833/193963475-e237f672-0063-47f4-8e24-643b6b600606.png)

**Comment by stasm** [comment]
Nice analysis :) To be fair, we didn't expect most people to play Afterlife for more than 5 minutes. It's a jam game, and it's understandable that the attention span of participants is short.

**Comment by tronster** [comment]
I know this was a little over the top. ;)  Thanks for the replies, comments in the code, and bravo on the game - one of my favorites from the jam.
